// Voice Agent Implementation
// Generated by eleven-cursor CLI

const { ElevenLabsClient } = require('elevenlabs');

class VoiceAgent {
  constructor(config) {
    this.client = new ElevenLabsClient({ apiKey: config.apiKey });
    this.voiceId = config.voiceId;
    this.settings = config.settings;
  }

  async speak(text, options = {}) {
    try {
      const audio = await this.client.generate({
        voice: this.voiceId,
        text: text,
        voice_settings: { ...this.settings, ...options.settings }
      });
      
      return audio;
    } catch (error) {
      throw new Error(`Voice synthesis failed: ${error.message}`);
    }
  }

  updateSettings(newSettings) {
    this.settings = { ...this.settings, ...newSettings };
  }
}

module.exports = VoiceAgent;